name: build on windows amd64 preview native
on:
  push:
    branches:
      - main
jobs:
  build:
    name: ZrLog on ${{ matrix.os }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        architecture: [ x86 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm' # See 'Options' for all available distributions
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and upload binary
        run: |
          rm src/main/resources/lib/aarch64/linux/mysqldump
          rm src/main/resources/lib/aarch64/macosx/mysqldump
          rm src/main/resources/lib/x86_64/linux/mysqldump
          rm src/main/resources/lib/x86_64/macosx/mysqldump
          bash -e bin/package-native-github.sh
          bash -e bin/upload-bin-windows.sh ${{ secrets.SECRET_ID }} ${{ secrets.SECRET_KEY }} ${{ secrets.BUCKET }} /tmp/download plugin